//FALTA FAZER NO PROGRAMA:

// - REsPOSTA "NAO" DA PERGUNTA DE INICIAR PEDIDO APOS CARDAPIO
// - INFORMAR CODIGO PEDIDO APOS JA SABER O PEDIDO
//	- CADASTRO DE CLIENTE
//	- FECHAMDNO DE CONTA ORGANIZADO
// - FECHAMENTO DE CONTA DIVIDINDO PELO NUMERO DE USUARIOS NA MESA
// - FORMA DE PAGAMENTO
// - ENVIAR CONTA PARA PDF
// - PASSAR PARA GUI (SWING)
